#!/usr/bin/env bash

set -e
set -x

# Update as necessary
git config --global user.name "Thomas Rambø"
git config --global user.email "thms.rmb@gmail.com"

git config --global gpg.format ssh
git config --global commit.gpgsign true
git config --global user.signingKey ~/.ssh/id_ed25519.pub
